[2023-04-01T13:19:13.104+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_status_with_image_update.tweet_image scheduled__2023-03-31T00:00:00+00:00 [queued]>
[2023-04-01T13:19:13.117+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: twitter_status_with_image_update.tweet_image scheduled__2023-03-31T00:00:00+00:00 [queued]>
[2023-04-01T13:19:13.118+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-04-01T13:19:13.120+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 3
[2023-04-01T13:19:13.121+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-04-01T13:19:13.136+0000] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): tweet_image> on 2023-03-31 00:00:00+00:00
[2023-04-01T13:19:13.143+0000] {standard_task_runner.py:55} INFO - Started process 12365 to run task
[2023-04-01T13:19:13.146+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'twitter_status_with_image_update', 'tweet_image', 'scheduled__2023-03-31T00:00:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/twitterImageWithTextUpdatePipeline.py', '--cfg-path', '/tmp/tmp5ld9timk']
[2023-04-01T13:19:13.148+0000] {standard_task_runner.py:83} INFO - Job 123: Subtask tweet_image
[2023-04-01T13:19:13.199+0000] {task_command.py:388} INFO - Running <TaskInstance: twitter_status_with_image_update.tweet_image scheduled__2023-03-31T00:00:00+00:00 [running]> on host 21dcead862af
[2023-04-01T13:19:13.263+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=twitter_status_with_image_update
AIRFLOW_CTX_TASK_ID=tweet_image
AIRFLOW_CTX_EXECUTION_DATE=2023-03-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-31T00:00:00+00:00
[2023-04-01T13:19:13.266+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/twitterImageWithTextUpdatePipeline.py", line 51, in tweet_image
    image_name = image_details["image_name"]
KeyError: 'image_name'
[2023-04-01T13:19:13.276+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_status_with_image_update, task_id=tweet_image, execution_date=20230331T000000, start_date=20230401T131913, end_date=20230401T131913
[2023-04-01T13:19:13.286+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 123 for task tweet_image ('image_name'; 12365)
[2023-04-01T13:19:13.319+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-04-01T13:19:13.334+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
